with catalog(name, category, display_order) as (values
('Passport', 'Identity and Personal Documents', 1),
('National ID Card', 'Identity and Personal Documents', 2),
('National Identity Number Document', 'Identity and Personal Documents', 3),
('Birth Certificate', 'Identity and Personal Documents', 4),
('Age Declaration', 'Identity and Personal Documents', 5),
('Affidavit of Birth', 'Identity and Personal Documents', 6),
('Marriage Certificate', 'Identity and Personal Documents', 7),
('Divorce Certificate', 'Identity and Personal Documents', 8),
('Change of Name Certificate', 'Identity and Personal Documents', 9),
('Deed Poll', 'Identity and Personal Documents', 10),
('Name Affidavit', 'Identity and Personal Documents', 11),
('Death Certificate', 'Identity and Personal Documents', 12),
('Family Registration Document', 'Identity and Personal Documents', 13),
('Residence Permit', 'Identity and Personal Documents', 14),
('Permanent Residence Card', 'Identity and Personal Documents', 15),
('Previous Passport', 'Identity and Personal Documents', 16),
('Passport Photograph', 'Identity and Personal Documents', 17),
('Passport Bio Page', 'Identity and Personal Documents', 18),
('Visa', 'Identity and Personal Documents', 19),
('Previous Visa', 'Identity and Personal Documents', 20),
('Immigration Status Document', 'Identity and Personal Documents', 21),
('Residence Card', 'Identity and Personal Documents', 22),
('Proof of Address', 'Identity and Personal Documents', 23),
('Utility Bill', 'Identity and Personal Documents', 24),
('Government Correspondence', 'Identity and Personal Documents', 25),
('Secondary School Certificate', 'Academic Documents', 26),
('High School Certificate', 'Academic Documents', 27),
('WAEC Certificate', 'Academic Documents', 28),
('NECO Certificate', 'Academic Documents', 29),
('GCE Certificate', 'Academic Documents', 30),
('NABTEB Certificate', 'Academic Documents', 31),
('GCSE Certificate', 'Academic Documents', 32),
('A-Level Certificate', 'Academic Documents', 33),
('O-Level Certificate', 'Academic Documents', 34),
('SSCE Certificate', 'Academic Documents', 35),
('High School Transcript', 'Academic Documents', 36),
('Secondary School Transcript', 'Academic Documents', 37),
('School Result', 'Academic Documents', 38),
('Statement of Result', 'Academic Documents', 39),
('Academic Transcript', 'Academic Documents', 40),
('University Transcript', 'Academic Documents', 41),
('Undergraduate Transcript', 'Academic Documents', 42),
('Postgraduate Transcript', 'Academic Documents', 43),
('Degree Certificate', 'Academic Documents', 44),
('Bachelor''s Degree Certificate', 'Academic Documents', 45),
('Master''s Degree Certificate', 'Academic Documents', 46),
('PhD Certificate', 'Academic Documents', 47),
('Diploma Certificate', 'Academic Documents', 48),
('Higher National Diploma', 'Academic Documents', 49),
('National Diploma', 'Academic Documents', 50),
('Foundation Certificate', 'Academic Documents', 51),
('Foundation Programme Certificate', 'Academic Documents', 52),
('Pre-Master''s Certificate', 'Academic Documents', 53),
('Professional Certificate', 'Academic Documents', 54),
('Professional Qualification', 'Academic Documents', 55),
('Professional Examination Result', 'Academic Documents', 56),
('Academic Record', 'Academic Documents', 57),
('Graduation Certificate', 'Academic Documents', 58),
('Graduation Letter', 'Academic Documents', 59),
('Completion Letter', 'Academic Documents', 60),
('Certificate of Completion', 'Academic Documents', 61),
('Certificate of Attendance', 'Academic Documents', 62),
('Academic Reference', 'Academic Documents', 63),
('School Reference', 'Academic Documents', 64),
('University Reference', 'Academic Documents', 65),
('Academic Recommendation Letter', 'Academic Documents', 66),
('Academic Progress Report', 'Academic Documents', 67),
('Student Status Letter', 'Academic Documents', 68),
('Enrollment Letter', 'Academic Documents', 69),
('Confirmation of Enrollment', 'Academic Documents', 70),
('Letter of Good Standing', 'Academic Documents', 71),
('Transfer Certificate', 'Academic Documents', 72),
('Withdrawal Letter', 'Academic Documents', 73),
('Academic Withdrawal Letter', 'Academic Documents', 74),
('Course Completion Letter', 'Academic Documents', 75),
('Medium of Instruction Letter', 'Academic Documents', 76),
('English as Medium of Instruction Letter', 'Academic Documents', 77),
('Academic Verification Letter', 'Academic Documents', 78),
('IELTS', 'English Language Documents', 79),
('IELTS Academic', 'English Language Documents', 80),
('IELTS General Training', 'English Language Documents', 81),
('IELTS UKVI', 'English Language Documents', 82),
('IELTS Life Skills', 'English Language Documents', 83),
('TOEFL', 'English Language Documents', 84),
('TOEFL iBT', 'English Language Documents', 85),
('PTE', 'English Language Documents', 86),
('PTE Academic', 'English Language Documents', 87),
('PTE Academic UKVI', 'English Language Documents', 88),
('Cambridge English', 'English Language Documents', 89),
('Cambridge C1 Advanced', 'English Language Documents', 90),
('Cambridge C2 Proficiency', 'English Language Documents', 91),
('OET', 'English Language Documents', 92),
('Duolingo English Test', 'English Language Documents', 93),
('LanguageCert', 'English Language Documents', 94),
('Trinity College London Certificate', 'English Language Documents', 95),
('English Language Certificate', 'English Language Documents', 96),
('English Proficiency Certificate', 'English Language Documents', 97),
('English Language Waiver', 'English Language Documents', 98),
('English Language Exemption Letter', 'English Language Documents', 99),
('University English Assessment', 'English Language Documents', 100),
('Internal English Test Result', 'English Language Documents', 101),
('CV', 'CV and Employment Documents', 102),
('Resume', 'CV and Employment Documents', 103),
('Europass CV', 'CV and Employment Documents', 104),
('Academic CV', 'CV and Employment Documents', 105),
('Professional CV', 'CV and Employment Documents', 106),
('Employment Letter', 'CV and Employment Documents', 107),
('Employment Verification Letter', 'CV and Employment Documents', 108),
('Work Experience Letter', 'CV and Employment Documents', 109),
('Experience Certificate', 'CV and Employment Documents', 110),
('Employer Reference', 'CV and Employment Documents', 111),
('Professional Reference', 'CV and Employment Documents', 112),
('Job Offer Letter', 'CV and Employment Documents', 113),
('Employment Contract', 'CV and Employment Documents', 114),
('Promotion Letter', 'CV and Employment Documents', 115),
('Appointment Letter', 'CV and Employment Documents', 116),
('Internship Certificate', 'CV and Employment Documents', 117),
('Internship Letter', 'CV and Employment Documents', 118),
('Internship Completion Letter', 'CV and Employment Documents', 119),
('Payslip', 'CV and Employment Documents', 120),
('Salary Slip', 'CV and Employment Documents', 121),
('Salary Certificate', 'CV and Employment Documents', 122),
('Employment History', 'CV and Employment Documents', 123),
('Work History', 'CV and Employment Documents', 124),
('Professional Portfolio', 'CV and Employment Documents', 125),
('LinkedIn Profile Export', 'CV and Employment Documents', 126),
('Career History Statement', 'CV and Employment Documents', 127),
('Gap Explanation Letter', 'CV and Employment Documents', 128),
('Employment Gap Explanation', 'CV and Employment Documents', 129),
('Resignation Letter', 'CV and Employment Documents', 130),
('Termination Letter', 'CV and Employment Documents', 131),
('Self-Employment Evidence', 'CV and Employment Documents', 132),
('Business Registration Document', 'CV and Employment Documents', 133),
('Bank Statement', 'Financial Documents', 134),
('Bank Account Statement', 'Financial Documents', 135),
('Savings Account Statement', 'Financial Documents', 136),
('Current Account Statement', 'Financial Documents', 137),
('Fixed Deposit Statement', 'Financial Documents', 138),
('Certificate of Deposit', 'Financial Documents', 139),
('Bank Certificate', 'Financial Documents', 140),
('Bank Balance Confirmation', 'Financial Documents', 141),
('Bank Reference Letter', 'Financial Documents', 142),
('Bank Verification Letter', 'Financial Documents', 143),
('Bank Letter', 'Financial Documents', 144),
('Account Confirmation Letter', 'Financial Documents', 145),
('Financial Statement', 'Financial Documents', 146),
('Proof of Funds', 'Financial Documents', 147),
('Proof of Financial Support', 'Financial Documents', 148),
('Financial Sponsorship Letter', 'Financial Documents', 149),
('Sponsor Letter', 'Financial Documents', 150),
('Sponsorship Letter', 'Financial Documents', 151),
('Father Sponsorship Letter', 'Financial Documents', 152),
('Mother Sponsorship Letter', 'Financial Documents', 153),
('Family Sponsorship Letter', 'Financial Documents', 154),
('Employer Sponsorship Letter', 'Financial Documents', 155),
('Government Sponsorship Letter', 'Financial Documents', 156),
('Scholarship Sponsorship Letter', 'Financial Documents', 157),
('Scholarship Letter', 'Financial Documents', 158),
('Scholarship Award Letter', 'Financial Documents', 159),
('Scholarship Confirmation', 'Financial Documents', 160),
('Student Loan Letter', 'Financial Documents', 161),
('Education Loan Approval', 'Financial Documents', 162),
('Loan Statement', 'Financial Documents', 163),
('Loan Disbursement Letter', 'Financial Documents', 164),
('Tax Certificate', 'Financial Documents', 165),
('Tax Return', 'Financial Documents', 166),
('Tax Clearance Certificate', 'Financial Documents', 167),
('Tax Assessment', 'Financial Documents', 168),
('Income Certificate', 'Financial Documents', 169),
('Income Statement', 'Financial Documents', 170),
('Salary Evidence', 'Financial Documents', 171),
('Payslips', 'Financial Documents', 172),
('Pension Statement', 'Financial Documents', 173),
('Investment Statement', 'Financial Documents', 174),
('Investment Certificate', 'Financial Documents', 175),
('Property Valuation', 'Financial Documents', 176),
('Property Ownership Document', 'Financial Documents', 177),
('Land Document', 'Financial Documents', 178),
('Deed of Ownership', 'Financial Documents', 179),
('Rental Income Evidence', 'Financial Documents', 180),
('Business Income Evidence', 'Financial Documents', 181),
('Business Account Statement', 'Financial Documents', 182),
('Company Bank Statement', 'Financial Documents', 183),
('Company Financial Statement', 'Financial Documents', 184),
('Source of Funds Evidence', 'Financial Documents', 185),
('Source of Wealth Evidence', 'Financial Documents', 186),
('Large Deposit Explanation', 'Financial Documents', 187),
('Deposit Explanation Letter', 'Financial Documents', 188),
('Financial Affidavit', 'Financial Documents', 189),
('Sponsorship Declaration', 'Sponsor Documents', 190),
('Sponsor Affidavit', 'Sponsor Documents', 191),
('Sponsor Bank Statement', 'Sponsor Documents', 192),
('Sponsor Bank Letter', 'Sponsor Documents', 193),
('Sponsor Payslip', 'Sponsor Documents', 194),
('Sponsor Employment Letter', 'Sponsor Documents', 195),
('Sponsor Salary Certificate', 'Sponsor Documents', 196),
('Sponsor Tax Certificate', 'Sponsor Documents', 197),
('Sponsor Tax Return', 'Sponsor Documents', 198),
('Sponsor ID', 'Sponsor Documents', 199),
('Sponsor Passport', 'Sponsor Documents', 200),
('Sponsor Residence Permit', 'Sponsor Documents', 201),
('Sponsor Proof of Address', 'Sponsor Documents', 202),
('Sponsor Relationship Evidence', 'Sponsor Documents', 203),
('Birth Certificate Showing Relationship', 'Sponsor Documents', 204),
('Marriage Certificate Showing Relationship', 'Sponsor Documents', 205),
('Sponsor Business Registration', 'Sponsor Documents', 206),
('Sponsor Business Account Statement', 'Sponsor Documents', 207),
('Sponsor Business Financial Statement', 'Sponsor Documents', 208),
('Sponsor Property Evidence', 'Sponsor Documents', 209),
('Sponsor Income Evidence', 'Sponsor Documents', 210),
('University Application Form', 'University Application Documents', 211),
('Online Application Form', 'University Application Documents', 212),
('Application Summary', 'University Application Documents', 213),
('Application Confirmation', 'University Application Documents', 214),
('Application Receipt', 'University Application Documents', 215),
('Application Reference Letter', 'University Application Documents', 216),
('Application Reference Number', 'University Application Documents', 217),
('Personal Statement', 'University Application Documents', 218),
('Statement of Purpose', 'University Application Documents', 219),
('SOP', 'University Application Documents', 220),
('Motivation Letter', 'University Application Documents', 221),
('Motivation Statement', 'University Application Documents', 222),
('Study Plan', 'University Application Documents', 223),
('Research Proposal', 'University Application Documents', 224),
('Research Statement', 'University Application Documents', 225),
('Academic Statement', 'University Application Documents', 226),
('Personal Essay', 'University Application Documents', 227),
('Scholarship Essay', 'University Application Documents', 228),
('Scholarship Application', 'University Application Documents', 229),
('Scholarship Form', 'University Application Documents', 230),
('Scholarship Statement', 'University Application Documents', 231),
('Recommendation Letter', 'University Application Documents', 232),
('Reference Letter', 'University Application Documents', 233),
('Letter of Intent', 'University Application Documents', 234),
('Letter of Explanation', 'University Application Documents', 235),
('Cover Letter', 'University Application Documents', 236),
('Portfolio', 'University Application Documents', 237),
('Writing Sample', 'University Application Documents', 238),
('Published Work', 'University Application Documents', 239),
('Academic Publication', 'University Application Documents', 240),
('Research Paper', 'University Application Documents', 241),
('Dissertation', 'University Application Documents', 242),
('Thesis', 'University Application Documents', 243),
('Project Proposal', 'University Application Documents', 244),
('Offer Letter', 'Admission Documents', 245),
('Conditional Offer Letter', 'Admission Documents', 246),
('Unconditional Offer Letter', 'Admission Documents', 247),
('Admission Letter', 'Admission Documents', 248),
('Acceptance Letter', 'Admission Documents', 249),
('Admission Confirmation', 'Admission Documents', 250),
('Conditional Admission Letter', 'Admission Documents', 251),
('Unconditional Admission Letter', 'Admission Documents', 252),
('Enrollment Confirmation', 'Admission Documents', 253),
('CAS', 'Admission Documents', 254),
('CAS Statement', 'Admission Documents', 255),
('CAS Email', 'Admission Documents', 256),
('Confirmation of Acceptance for Studies', 'Admission Documents', 257),
('Deposit Receipt', 'Admission Documents', 258),
('Tuition Fee Receipt', 'Admission Documents', 259),
('Tuition Payment Confirmation', 'Admission Documents', 260),
('Deposit Confirmation', 'Admission Documents', 261),
('Fee Assessment', 'Admission Documents', 262),
('Fee Invoice', 'Admission Documents', 263),
('Tuition Fee Invoice', 'Admission Documents', 264),
('Payment Plan', 'Admission Documents', 265),
('University Invoice', 'Admission Documents', 266),
('Accommodation Confirmation', 'Admission Documents', 267),
('University Accommodation Letter', 'Admission Documents', 268),
('Visa Application Form', 'Visa and Immigration Documents', 269),
('Visa Appointment Confirmation', 'Visa and Immigration Documents', 270),
('Visa Application Confirmation', 'Visa and Immigration Documents', 271),
('Visa Fee Receipt', 'Visa and Immigration Documents', 272),
('Biometrics Appointment', 'Visa and Immigration Documents', 273),
('Biometrics Confirmation', 'Visa and Immigration Documents', 274),
('Immigration Health Surcharge Receipt', 'Visa and Immigration Documents', 275),
('IHS Receipt', 'Visa and Immigration Documents', 276),
('Visa Decision Letter', 'Visa and Immigration Documents', 277),
('Visa Grant Letter', 'Visa and Immigration Documents', 278),
('Visa Refusal Letter', 'Visa and Immigration Documents', 279),
('Visa Refusal Explanation', 'Visa and Immigration Documents', 280),
('Immigration Correspondence', 'Visa and Immigration Documents', 281),
('Immigration History', 'Visa and Immigration Documents', 282),
('Previous Visa Decision', 'Visa and Immigration Documents', 283),
('Previous Visa Refusal', 'Visa and Immigration Documents', 284),
('BRP-related Document', 'Visa and Immigration Documents', 285),
('eVisa Evidence', 'Visa and Immigration Documents', 286),
('Share Code', 'Visa and Immigration Documents', 287),
('Immigration Status Share Code', 'Visa and Immigration Documents', 288),
('Right to Study Evidence', 'Visa and Immigration Documents', 289),
('Right to Work Evidence', 'Visa and Immigration Documents', 290),
('Previous Immigration Documents', 'Visa and Immigration Documents', 291),
('Travel History', 'Visa and Immigration Documents', 292),
('Entry Clearance Document', 'Visa and Immigration Documents', 293),
('Exit Clearance Document', 'Visa and Immigration Documents', 294),
('ATAS Certificate', 'UK-Specific Documents', 295),
('TB Certificate', 'UK-Specific Documents', 296),
('UKVI Financial Evidence', 'UK-Specific Documents', 297),
('UKVI Bank Statement', 'UK-Specific Documents', 298),
('UKVI Sponsor Evidence', 'UK-Specific Documents', 299),
('UKVI Visa Application', 'UK-Specific Documents', 300),
('UKVI Decision Letter', 'UK-Specific Documents', 301),
('UKVI Refusal Letter', 'UK-Specific Documents', 302),
('Biometric Appointment Letter', 'UK-Specific Documents', 303),
('eVisa', 'UK-Specific Documents', 304),
('BRP Evidence', 'UK-Specific Documents', 305),
('Academic Technology Approval Scheme Certificate', 'UK-Specific Documents', 306),
('UK Accommodation Evidence', 'UK-Specific Documents', 307),
('UKVI Correspondence', 'UK-Specific Documents', 308),
('Previous UK Visa', 'UK-Specific Documents', 309),
('Previous UK Visa Refusal', 'UK-Specific Documents', 310),
('Medical Certificate', 'Medical Documents', 311),
('Medical Examination Report', 'Medical Documents', 312),
('Medical Fitness Certificate', 'Medical Documents', 313),
('Medical History', 'Medical Documents', 314),
('Vaccination Record', 'Medical Documents', 315),
('Immunization Record', 'Medical Documents', 316),
('Vaccination Certificate', 'Medical Documents', 317),
('TB Test Certificate', 'Medical Documents', 318),
('TB Screening Certificate', 'Medical Documents', 319),
('Medical Insurance Certificate', 'Medical Documents', 320),
('Health Insurance', 'Medical Documents', 321),
('Medical Clearance', 'Medical Documents', 322),
('Disability Documentation', 'Medical Documents', 323),
('Medical Accommodation Letter', 'Medical Documents', 324),
('Affidavit', 'Legal and Supporting Documents', 325),
('Statutory Declaration', 'Legal and Supporting Documents', 326),
('Declaration Letter', 'Legal and Supporting Documents', 327),
('Legal Declaration', 'Legal and Supporting Documents', 328),
('Court Order', 'Legal and Supporting Documents', 329),
('Court Document', 'Legal and Supporting Documents', 330),
('Power of Attorney', 'Legal and Supporting Documents', 331),
('Guardianship Document', 'Legal and Supporting Documents', 332),
('Custody Document', 'Legal and Supporting Documents', 333),
('Adoption Certificate', 'Legal and Supporting Documents', 334),
('Legal Name Change Document', 'Legal and Supporting Documents', 335),
('Police Clearance Certificate', 'Legal and Supporting Documents', 336),
('Criminal Record Certificate', 'Legal and Supporting Documents', 337),
('Character Certificate', 'Legal and Supporting Documents', 338),
('Good Conduct Certificate', 'Legal and Supporting Documents', 339),
('Certificate of Good Character', 'Legal and Supporting Documents', 340),
('Notarised Document', 'Legal and Supporting Documents', 341),
('Certified Copy', 'Legal and Supporting Documents', 342),
('Certified Translation', 'Legal and Supporting Documents', 343),
('Legal Translation', 'Legal and Supporting Documents', 344),
('Translation Certificate', 'Legal and Supporting Documents', 345),
('Translator Declaration', 'Legal and Supporting Documents', 346),
('Family Registration', 'Family and Relationship Documents', 347),
('Family Tree Document', 'Family and Relationship Documents', 348),
('Relationship Affidavit', 'Family and Relationship Documents', 349),
('Proof of Relationship', 'Family and Relationship Documents', 350),
('Spouse Evidence', 'Family and Relationship Documents', 351),
('Parent Evidence', 'Family and Relationship Documents', 352),
('Child Birth Certificate', 'Family and Relationship Documents', 353),
('Custody Order', 'Family and Relationship Documents', 354),
('Accommodation Letter', 'Accommodation Documents', 355),
('Accommodation Booking', 'Accommodation Documents', 356),
('University Accommodation Confirmation', 'Accommodation Documents', 357),
('Tenancy Agreement', 'Accommodation Documents', 358),
('Rental Agreement', 'Accommodation Documents', 359),
('Lease Agreement', 'Accommodation Documents', 360),
('Landlord Letter', 'Accommodation Documents', 361),
('Landlord ID', 'Accommodation Documents', 362),
('Proof of Accommodation', 'Accommodation Documents', 363),
('Hotel Booking', 'Accommodation Documents', 364),
('Temporary Accommodation Booking', 'Accommodation Documents', 365),
('Address Confirmation', 'Accommodation Documents', 366),
('Council Tax Document', 'Accommodation Documents', 367),
('Flight Reservation', 'Travel Documents', 368),
('Flight Booking', 'Travel Documents', 369),
('Travel Itinerary', 'Travel Documents', 370),
('Previous Travel Visa', 'Travel Documents', 371),
('Entry Stamp', 'Travel Documents', 372),
('Exit Stamp', 'Travel Documents', 373),
('Travel Insurance', 'Travel Documents', 374),
('International Travel Insurance', 'Travel Documents', 375),
('Certificate of Incorporation', 'Business Documents', 376),
('Business Registration Certificate', 'Business Documents', 377),
('CAC Certificate', 'Business Documents', 378),
('CAC Form', 'Business Documents', 379),
('Memorandum and Articles', 'Business Documents', 380),
('Company Profile', 'Business Documents', 381),
('Business Licence', 'Business Documents', 382),
('Business Permit', 'Business Documents', 383),
('Tax Registration', 'Business Documents', 384),
('Tax Clearance', 'Business Documents', 385),
('Company Tax Return', 'Business Documents', 386),
('Business Bank Statement', 'Business Documents', 387),
('Audited Accounts', 'Business Documents', 388),
('Director Information', 'Business Documents', 389),
('Shareholder Information', 'Business Documents', 390),
('Business Ownership Evidence', 'Business Documents', 391),
('Business Contract', 'Business Documents', 392),
('Invoice', 'Business Documents', 393),
('Business Agreement', 'Business Documents', 394),
('Professional Licence', 'Professional Qualification Documents', 395),
('Professional Registration', 'Professional Qualification Documents', 396),
('Professional Membership', 'Professional Qualification Documents', 397),
('Nursing Licence', 'Professional Qualification Documents', 398),
('Medical Licence', 'Professional Qualification Documents', 399),
('Pharmacy Licence', 'Professional Qualification Documents', 400),
('Engineering Licence', 'Professional Qualification Documents', 401),
('Teaching Licence', 'Professional Qualification Documents', 402),
('Accounting Qualification', 'Professional Qualification Documents', 403),
('ACCA Certificate', 'Professional Qualification Documents', 404),
('ICAN Certificate', 'Professional Qualification Documents', 405),
('CFA Certificate', 'Professional Qualification Documents', 406),
('PMP Certificate', 'Professional Qualification Documents', 407),
('Other Professional Qualification', 'Professional Qualification Documents', 408),
('PhD Proposal', 'Research and PhD Documents', 409),
('Research Plan', 'Research and PhD Documents', 410),
('Published Research', 'Research and PhD Documents', 411),
('Conference Paper', 'Research and PhD Documents', 412),
('Conference Certificate', 'Research and PhD Documents', 413),
('Supervisor Letter', 'Research and PhD Documents', 414),
('Supervisor Acceptance Letter', 'Research and PhD Documents', 415),
('Research Supervisor Confirmation', 'Research and PhD Documents', 416),
('Funding Letter', 'Research and PhD Documents', 417),
('Research Funding Evidence', 'Research and PhD Documents', 418),
('Publication List', 'Research and PhD Documents', 419),
('Research Portfolio', 'Research and PhD Documents', 420),
('Art Portfolio', 'Portfolio and Creative Documents', 421),
('Design Portfolio', 'Portfolio and Creative Documents', 422),
('Architecture Portfolio', 'Portfolio and Creative Documents', 423),
('Photography Portfolio', 'Portfolio and Creative Documents', 424),
('Graphic Design Portfolio', 'Portfolio and Creative Documents', 425),
('Fashion Portfolio', 'Portfolio and Creative Documents', 426),
('Video Portfolio', 'Portfolio and Creative Documents', 427),
('Creative Work Sample', 'Portfolio and Creative Documents', 428),
('Writing Portfolio', 'Portfolio and Creative Documents', 429),
('Project Portfolio', 'Portfolio and Creative Documents', 430),
('GitHub Profile', 'Portfolio and Creative Documents', 431),
('Coding Portfolio', 'Portfolio and Creative Documents', 432),
('Website Portfolio', 'Portfolio and Creative Documents', 433)
)
update public.document_types d
set category = c.category, display_order = c.display_order, slug = regexp_replace(regexp_replace(lower(d.name), '[^a-z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')
from catalog c
where lower(d.name) = lower(c.name);