alter table public.document_types add column if not exists category text not null default 'Other';
alter table public.document_types add column if not exists slug text;
alter table public.document_types add column if not exists display_order integer not null default 1000;
update public.document_types set slug = regexp_replace(regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g'), '(^-|-$)', '', 'g') where slug is null;
create index if not exists document_types_category_idx on public.document_types(category);
create index if not exists document_types_slug_idx on public.document_types(slug);

with catalog(name, category, slug) as (values
('Passport', 'Identity and Personal Documents', 'passport'),
('National ID Card', 'Identity and Personal Documents', 'national-id-card'),
('National Identity Number Document', 'Identity and Personal Documents', 'national-identity-number-document'),
('Birth Certificate', 'Identity and Personal Documents', 'birth-certificate'),
('Age Declaration', 'Identity and Personal Documents', 'age-declaration'),
('Affidavit of Birth', 'Identity and Personal Documents', 'affidavit-of-birth'),
('Marriage Certificate', 'Identity and Personal Documents', 'marriage-certificate'),
('Divorce Certificate', 'Identity and Personal Documents', 'divorce-certificate'),
('Change of Name Certificate', 'Identity and Personal Documents', 'change-of-name-certificate'),
('Deed Poll', 'Identity and Personal Documents', 'deed-poll'),
('Name Affidavit', 'Identity and Personal Documents', 'name-affidavit'),
('Death Certificate', 'Identity and Personal Documents', 'death-certificate'),
('Family Registration Document', 'Identity and Personal Documents', 'family-registration-document'),
('Residence Permit', 'Identity and Personal Documents', 'residence-permit'),
('Permanent Residence Card', 'Identity and Personal Documents', 'permanent-residence-card'),
('Previous Passport', 'Identity and Personal Documents', 'previous-passport'),
('Passport Photograph', 'Identity and Personal Documents', 'passport-photograph'),
('Passport Bio Page', 'Identity and Personal Documents', 'passport-bio-page'),
('Visa', 'Identity and Personal Documents', 'visa'),
('Previous Visa', 'Identity and Personal Documents', 'previous-visa'),
('Immigration Status Document', 'Identity and Personal Documents', 'immigration-status-document'),
('Residence Card', 'Identity and Personal Documents', 'residence-card'),
('Proof of Address', 'Identity and Personal Documents', 'proof-of-address'),
('Utility Bill', 'Identity and Personal Documents', 'utility-bill'),
('Government Correspondence', 'Identity and Personal Documents', 'government-correspondence'),
('Secondary School Certificate', 'Academic Documents', 'secondary-school-certificate'),
('High School Certificate', 'Academic Documents', 'high-school-certificate'),
('WAEC Certificate', 'Academic Documents', 'waec-certificate'),
('NECO Certificate', 'Academic Documents', 'neco-certificate'),
('GCE Certificate', 'Academic Documents', 'gce-certificate'),
('NABTEB Certificate', 'Academic Documents', 'nabteb-certificate'),
('GCSE Certificate', 'Academic Documents', 'gcse-certificate'),
('A-Level Certificate', 'Academic Documents', 'a-level-certificate'),
('O-Level Certificate', 'Academic Documents', 'o-level-certificate'),
('SSCE Certificate', 'Academic Documents', 'ssce-certificate'),
('High School Transcript', 'Academic Documents', 'high-school-transcript'),
('Secondary School Transcript', 'Academic Documents', 'secondary-school-transcript'),
('School Result', 'Academic Documents', 'school-result'),
('Statement of Result', 'Academic Documents', 'statement-of-result'),
('Academic Transcript', 'Academic Documents', 'academic-transcript'),
('University Transcript', 'Academic Documents', 'university-transcript'),
('Undergraduate Transcript', 'Academic Documents', 'undergraduate-transcript'),
('Postgraduate Transcript', 'Academic Documents', 'postgraduate-transcript'),
('Degree Certificate', 'Academic Documents', 'degree-certificate'),
('Bachelor''s Degree Certificate', 'Academic Documents', 'bachelor-s-degree-certificate'),
('Master''s Degree Certificate', 'Academic Documents', 'master-s-degree-certificate'),
('PhD Certificate', 'Academic Documents', 'phd-certificate'),
('Diploma Certificate', 'Academic Documents', 'diploma-certificate'),
('Higher National Diploma', 'Academic Documents', 'higher-national-diploma'),
('National Diploma', 'Academic Documents', 'national-diploma'),
('Foundation Certificate', 'Academic Documents', 'foundation-certificate'),
('Foundation Programme Certificate', 'Academic Documents', 'foundation-programme-certificate'),
('Pre-Master''s Certificate', 'Academic Documents', 'pre-master-s-certificate'),
('Professional Certificate', 'Academic Documents', 'professional-certificate'),
('Professional Qualification', 'Academic Documents', 'professional-qualification'),
('Professional Examination Result', 'Academic Documents', 'professional-examination-result'),
('Academic Record', 'Academic Documents', 'academic-record'),
('Graduation Certificate', 'Academic Documents', 'graduation-certificate'),
('Graduation Letter', 'Academic Documents', 'graduation-letter'),
('Completion Letter', 'Academic Documents', 'completion-letter'),
('Certificate of Completion', 'Academic Documents', 'certificate-of-completion'),
('Certificate of Attendance', 'Academic Documents', 'certificate-of-attendance'),
('Academic Reference', 'Academic Documents', 'academic-reference'),
('School Reference', 'Academic Documents', 'school-reference'),
('University Reference', 'Academic Documents', 'university-reference'),
('Academic Recommendation Letter', 'Academic Documents', 'academic-recommendation-letter'),
('Academic Progress Report', 'Academic Documents', 'academic-progress-report'),
('Student Status Letter', 'Academic Documents', 'student-status-letter'),
('Enrollment Letter', 'Academic Documents', 'enrollment-letter'),
('Confirmation of Enrollment', 'Academic Documents', 'confirmation-of-enrollment'),
('Letter of Good Standing', 'Academic Documents', 'letter-of-good-standing'),
('Transfer Certificate', 'Academic Documents', 'transfer-certificate'),
('Withdrawal Letter', 'Academic Documents', 'withdrawal-letter'),
('Academic Withdrawal Letter', 'Academic Documents', 'academic-withdrawal-letter'),
('Course Completion Letter', 'Academic Documents', 'course-completion-letter'),
('Medium of Instruction Letter', 'Academic Documents', 'medium-of-instruction-letter'),
('English as Medium of Instruction Letter', 'Academic Documents', 'english-as-medium-of-instruction-letter'),
('Academic Verification Letter', 'Academic Documents', 'academic-verification-letter'),
('IELTS', 'English Language Documents', 'ielts'),
('IELTS Academic', 'English Language Documents', 'ielts-academic'),
('IELTS General Training', 'English Language Documents', 'ielts-general-training'),
('IELTS UKVI', 'English Language Documents', 'ielts-ukvi'),
('IELTS Life Skills', 'English Language Documents', 'ielts-life-skills'),
('TOEFL', 'English Language Documents', 'toefl'),
('TOEFL iBT', 'English Language Documents', 'toefl-ibt'),
('PTE', 'English Language Documents', 'pte'),
('PTE Academic', 'English Language Documents', 'pte-academic'),
('PTE Academic UKVI', 'English Language Documents', 'pte-academic-ukvi'),
('Cambridge English', 'English Language Documents', 'cambridge-english'),
('Cambridge C1 Advanced', 'English Language Documents', 'cambridge-c1-advanced'),
('Cambridge C2 Proficiency', 'English Language Documents', 'cambridge-c2-proficiency'),
('OET', 'English Language Documents', 'oet'),
('Duolingo English Test', 'English Language Documents', 'duolingo-english-test'),
('LanguageCert', 'English Language Documents', 'languagecert'),
('Trinity College London Certificate', 'English Language Documents', 'trinity-college-london-certificate'),
('English Language Certificate', 'English Language Documents', 'english-language-certificate'),
('English Proficiency Certificate', 'English Language Documents', 'english-proficiency-certificate'),
('English Language Waiver', 'English Language Documents', 'english-language-waiver'),
('English Language Exemption Letter', 'English Language Documents', 'english-language-exemption-letter'),
('University English Assessment', 'English Language Documents', 'university-english-assessment'),
('Internal English Test Result', 'English Language Documents', 'internal-english-test-result'),
('CV', 'CV and Employment Documents', 'cv'),
('Resume', 'CV and Employment Documents', 'resume'),
('Europass CV', 'CV and Employment Documents', 'europass-cv'),
('Academic CV', 'CV and Employment Documents', 'academic-cv'),
('Professional CV', 'CV and Employment Documents', 'professional-cv'),
('Employment Letter', 'CV and Employment Documents', 'employment-letter'),
('Employment Verification Letter', 'CV and Employment Documents', 'employment-verification-letter'),
('Work Experience Letter', 'CV and Employment Documents', 'work-experience-letter'),
('Experience Certificate', 'CV and Employment Documents', 'experience-certificate'),
('Employer Reference', 'CV and Employment Documents', 'employer-reference'),
('Professional Reference', 'CV and Employment Documents', 'professional-reference'),
('Job Offer Letter', 'CV and Employment Documents', 'job-offer-letter'),
('Employment Contract', 'CV and Employment Documents', 'employment-contract'),
('Promotion Letter', 'CV and Employment Documents', 'promotion-letter'),
('Appointment Letter', 'CV and Employment Documents', 'appointment-letter'),
('Internship Certificate', 'CV and Employment Documents', 'internship-certificate'),
('Internship Letter', 'CV and Employment Documents', 'internship-letter'),
('Internship Completion Letter', 'CV and Employment Documents', 'internship-completion-letter'),
('Payslip', 'CV and Employment Documents', 'payslip'),
('Salary Slip', 'CV and Employment Documents', 'salary-slip'),
('Salary Certificate', 'CV and Employment Documents', 'salary-certificate'),
('Employment History', 'CV and Employment Documents', 'employment-history'),
('Work History', 'CV and Employment Documents', 'work-history'),
('Professional Portfolio', 'CV and Employment Documents', 'professional-portfolio'),
('LinkedIn Profile Export', 'CV and Employment Documents', 'linkedin-profile-export'),
('Career History Statement', 'CV and Employment Documents', 'career-history-statement'),
('Gap Explanation Letter', 'CV and Employment Documents', 'gap-explanation-letter'),
('Employment Gap Explanation', 'CV and Employment Documents', 'employment-gap-explanation'),
('Resignation Letter', 'CV and Employment Documents', 'resignation-letter'),
('Termination Letter', 'CV and Employment Documents', 'termination-letter'),
('Self-Employment Evidence', 'CV and Employment Documents', 'self-employment-evidence'),
('Business Registration Document', 'CV and Employment Documents', 'business-registration-document'),
('Bank Statement', 'Financial Documents', 'bank-statement'),
('Bank Account Statement', 'Financial Documents', 'bank-account-statement'),
('Savings Account Statement', 'Financial Documents', 'savings-account-statement'),
('Current Account Statement', 'Financial Documents', 'current-account-statement'),
('Fixed Deposit Statement', 'Financial Documents', 'fixed-deposit-statement'),
('Certificate of Deposit', 'Financial Documents', 'certificate-of-deposit'),
('Bank Certificate', 'Financial Documents', 'bank-certificate'),
('Bank Balance Confirmation', 'Financial Documents', 'bank-balance-confirmation'),
('Bank Reference Letter', 'Financial Documents', 'bank-reference-letter'),
('Bank Verification Letter', 'Financial Documents', 'bank-verification-letter'),
('Bank Letter', 'Financial Documents', 'bank-letter'),
('Account Confirmation Letter', 'Financial Documents', 'account-confirmation-letter'),
('Financial Statement', 'Financial Documents', 'financial-statement'),
('Proof of Funds', 'Financial Documents', 'proof-of-funds'),
('Proof of Financial Support', 'Financial Documents', 'proof-of-financial-support'),
('Financial Sponsorship Letter', 'Financial Documents', 'financial-sponsorship-letter'),
('Sponsor Letter', 'Financial Documents', 'sponsor-letter'),
('Sponsorship Letter', 'Financial Documents', 'sponsorship-letter'),
('Father Sponsorship Letter', 'Financial Documents', 'father-sponsorship-letter'),
('Mother Sponsorship Letter', 'Financial Documents', 'mother-sponsorship-letter'),
('Family Sponsorship Letter', 'Financial Documents', 'family-sponsorship-letter'),
('Employer Sponsorship Letter', 'Financial Documents', 'employer-sponsorship-letter'),
('Government Sponsorship Letter', 'Financial Documents', 'government-sponsorship-letter'),
('Scholarship Sponsorship Letter', 'Financial Documents', 'scholarship-sponsorship-letter'),
('Scholarship Letter', 'Financial Documents', 'scholarship-letter'),
('Scholarship Award Letter', 'Financial Documents', 'scholarship-award-letter'),
('Scholarship Confirmation', 'Financial Documents', 'scholarship-confirmation'),
('Student Loan Letter', 'Financial Documents', 'student-loan-letter'),
('Education Loan Approval', 'Financial Documents', 'education-loan-approval'),
('Loan Statement', 'Financial Documents', 'loan-statement'),
('Loan Disbursement Letter', 'Financial Documents', 'loan-disbursement-letter'),
('Tax Certificate', 'Financial Documents', 'tax-certificate'),
('Tax Return', 'Financial Documents', 'tax-return'),
('Tax Clearance Certificate', 'Financial Documents', 'tax-clearance-certificate'),
('Tax Assessment', 'Financial Documents', 'tax-assessment'),
('Income Certificate', 'Financial Documents', 'income-certificate'),
('Income Statement', 'Financial Documents', 'income-statement'),
('Salary Evidence', 'Financial Documents', 'salary-evidence'),
('Payslips', 'Financial Documents', 'payslips'),
('Pension Statement', 'Financial Documents', 'pension-statement'),
('Investment Statement', 'Financial Documents', 'investment-statement'),
('Investment Certificate', 'Financial Documents', 'investment-certificate'),
('Property Valuation', 'Financial Documents', 'property-valuation'),
('Property Ownership Document', 'Financial Documents', 'property-ownership-document'),
('Land Document', 'Financial Documents', 'land-document'),
('Deed of Ownership', 'Financial Documents', 'deed-of-ownership'),
('Rental Income Evidence', 'Financial Documents', 'rental-income-evidence'),
('Business Income Evidence', 'Financial Documents', 'business-income-evidence'),
('Business Account Statement', 'Financial Documents', 'business-account-statement'),
('Company Bank Statement', 'Financial Documents', 'company-bank-statement'),
('Company Financial Statement', 'Financial Documents', 'company-financial-statement'),
('Source of Funds Evidence', 'Financial Documents', 'source-of-funds-evidence'),
('Source of Wealth Evidence', 'Financial Documents', 'source-of-wealth-evidence'),
('Large Deposit Explanation', 'Financial Documents', 'large-deposit-explanation'),
('Deposit Explanation Letter', 'Financial Documents', 'deposit-explanation-letter'),
('Financial Affidavit', 'Financial Documents', 'financial-affidavit'),
('Sponsorship Declaration', 'Sponsor Documents', 'sponsorship-declaration'),
('Sponsor Affidavit', 'Sponsor Documents', 'sponsor-affidavit'),
('Sponsor Bank Statement', 'Sponsor Documents', 'sponsor-bank-statement'),
('Sponsor Bank Letter', 'Sponsor Documents', 'sponsor-bank-letter'),
('Sponsor Payslip', 'Sponsor Documents', 'sponsor-payslip'),
('Sponsor Employment Letter', 'Sponsor Documents', 'sponsor-employment-letter'),
('Sponsor Salary Certificate', 'Sponsor Documents', 'sponsor-salary-certificate'),
('Sponsor Tax Certificate', 'Sponsor Documents', 'sponsor-tax-certificate'),
('Sponsor Tax Return', 'Sponsor Documents', 'sponsor-tax-return'),
('Sponsor ID', 'Sponsor Documents', 'sponsor-id'),
('Sponsor Passport', 'Sponsor Documents', 'sponsor-passport'),
('Sponsor Residence Permit', 'Sponsor Documents', 'sponsor-residence-permit'),
('Sponsor Proof of Address', 'Sponsor Documents', 'sponsor-proof-of-address'),
('Sponsor Relationship Evidence', 'Sponsor Documents', 'sponsor-relationship-evidence'),
('Birth Certificate Showing Relationship', 'Sponsor Documents', 'birth-certificate-showing-relationship'),
('Marriage Certificate Showing Relationship', 'Sponsor Documents', 'marriage-certificate-showing-relationship'),
('Sponsor Business Registration', 'Sponsor Documents', 'sponsor-business-registration'),
('Sponsor Business Account Statement', 'Sponsor Documents', 'sponsor-business-account-statement'),
('Sponsor Business Financial Statement', 'Sponsor Documents', 'sponsor-business-financial-statement'),
('Sponsor Property Evidence', 'Sponsor Documents', 'sponsor-property-evidence'),
('Sponsor Income Evidence', 'Sponsor Documents', 'sponsor-income-evidence'),
('University Application Form', 'University Application Documents', 'university-application-form'),
('Online Application Form', 'University Application Documents', 'online-application-form'),
('Application Summary', 'University Application Documents', 'application-summary'),
('Application Confirmation', 'University Application Documents', 'application-confirmation'),
('Application Receipt', 'University Application Documents', 'application-receipt'),
('Application Reference Letter', 'University Application Documents', 'application-reference-letter'),
('Application Reference Number', 'University Application Documents', 'application-reference-number'),
('Personal Statement', 'University Application Documents', 'personal-statement'),
('Statement of Purpose', 'University Application Documents', 'statement-of-purpose'),
('SOP', 'University Application Documents', 'sop'),
('Motivation Letter', 'University Application Documents', 'motivation-letter'),
('Motivation Statement', 'University Application Documents', 'motivation-statement'),
('Study Plan', 'University Application Documents', 'study-plan'),
('Research Proposal', 'University Application Documents', 'research-proposal'),
('Research Statement', 'University Application Documents', 'research-statement'),
('Academic Statement', 'University Application Documents', 'academic-statement'),
('Personal Essay', 'University Application Documents', 'personal-essay'),
('Scholarship Essay', 'University Application Documents', 'scholarship-essay'),
('Scholarship Application', 'University Application Documents', 'scholarship-application'),
('Scholarship Form', 'University Application Documents', 'scholarship-form'),
('Scholarship Statement', 'University Application Documents', 'scholarship-statement'),
('Recommendation Letter', 'University Application Documents', 'recommendation-letter'),
('Reference Letter', 'University Application Documents', 'reference-letter'),
('Letter of Intent', 'University Application Documents', 'letter-of-intent'),
('Letter of Explanation', 'University Application Documents', 'letter-of-explanation'),
('Cover Letter', 'University Application Documents', 'cover-letter'),
('Portfolio', 'University Application Documents', 'portfolio'),
('Writing Sample', 'University Application Documents', 'writing-sample'),
('Published Work', 'University Application Documents', 'published-work'),
('Academic Publication', 'University Application Documents', 'academic-publication'),
('Research Paper', 'University Application Documents', 'research-paper'),
('Dissertation', 'University Application Documents', 'dissertation'),
('Thesis', 'University Application Documents', 'thesis'),
('Project Proposal', 'University Application Documents', 'project-proposal'),
('Offer Letter', 'Admission Documents', 'offer-letter'),
('Conditional Offer Letter', 'Admission Documents', 'conditional-offer-letter'),
('Unconditional Offer Letter', 'Admission Documents', 'unconditional-offer-letter'),
('Admission Letter', 'Admission Documents', 'admission-letter'),
('Acceptance Letter', 'Admission Documents', 'acceptance-letter'),
('Admission Confirmation', 'Admission Documents', 'admission-confirmation'),
('Conditional Admission Letter', 'Admission Documents', 'conditional-admission-letter'),
('Unconditional Admission Letter', 'Admission Documents', 'unconditional-admission-letter'),
('Enrollment Confirmation', 'Admission Documents', 'enrollment-confirmation'),
('CAS', 'Admission Documents', 'cas'),
('CAS Statement', 'Admission Documents', 'cas-statement'),
('CAS Email', 'Admission Documents', 'cas-email'),
('Confirmation of Acceptance for Studies', 'Admission Documents', 'confirmation-of-acceptance-for-studies'),
('Deposit Receipt', 'Admission Documents', 'deposit-receipt'),
('Tuition Fee Receipt', 'Admission Documents', 'tuition-fee-receipt'),
('Tuition Payment Confirmation', 'Admission Documents', 'tuition-payment-confirmation'),
('Deposit Confirmation', 'Admission Documents', 'deposit-confirmation'),
('Fee Assessment', 'Admission Documents', 'fee-assessment'),
('Fee Invoice', 'Admission Documents', 'fee-invoice'),
('Tuition Fee Invoice', 'Admission Documents', 'tuition-fee-invoice'),
('Payment Plan', 'Admission Documents', 'payment-plan'),
('University Invoice', 'Admission Documents', 'university-invoice'),
('Accommodation Confirmation', 'Admission Documents', 'accommodation-confirmation'),
('University Accommodation Letter', 'Admission Documents', 'university-accommodation-letter'),
('Visa Application Form', 'Visa and Immigration Documents', 'visa-application-form'),
('Visa Appointment Confirmation', 'Visa and Immigration Documents', 'visa-appointment-confirmation'),
('Visa Application Confirmation', 'Visa and Immigration Documents', 'visa-application-confirmation'),
('Visa Fee Receipt', 'Visa and Immigration Documents', 'visa-fee-receipt'),
('Biometrics Appointment', 'Visa and Immigration Documents', 'biometrics-appointment'),
('Biometrics Confirmation', 'Visa and Immigration Documents', 'biometrics-confirmation'),
('Immigration Health Surcharge Receipt', 'Visa and Immigration Documents', 'immigration-health-surcharge-receipt'),
('IHS Receipt', 'Visa and Immigration Documents', 'ihs-receipt'),
('Visa Decision Letter', 'Visa and Immigration Documents', 'visa-decision-letter'),
('Visa Grant Letter', 'Visa and Immigration Documents', 'visa-grant-letter'),
('Visa Refusal Letter', 'Visa and Immigration Documents', 'visa-refusal-letter'),
('Visa Refusal Explanation', 'Visa and Immigration Documents', 'visa-refusal-explanation'),
('Immigration Correspondence', 'Visa and Immigration Documents', 'immigration-correspondence'),
('Immigration History', 'Visa and Immigration Documents', 'immigration-history'),
('Previous Visa Decision', 'Visa and Immigration Documents', 'previous-visa-decision'),
('Previous Visa Refusal', 'Visa and Immigration Documents', 'previous-visa-refusal'),
('BRP-related Document', 'Visa and Immigration Documents', 'brp-related-document'),
('eVisa Evidence', 'Visa and Immigration Documents', 'evisa-evidence'),
('Share Code', 'Visa and Immigration Documents', 'share-code'),
('Immigration Status Share Code', 'Visa and Immigration Documents', 'immigration-status-share-code'),
('Right to Study Evidence', 'Visa and Immigration Documents', 'right-to-study-evidence'),
('Right to Work Evidence', 'Visa and Immigration Documents', 'right-to-work-evidence'),
('Previous Immigration Documents', 'Visa and Immigration Documents', 'previous-immigration-documents'),
('Travel History', 'Visa and Immigration Documents', 'travel-history'),
('Entry Clearance Document', 'Visa and Immigration Documents', 'entry-clearance-document'),
('Exit Clearance Document', 'Visa and Immigration Documents', 'exit-clearance-document'),
('ATAS Certificate', 'UK-Specific Documents', 'atas-certificate'),
('TB Certificate', 'UK-Specific Documents', 'tb-certificate'),
('UKVI Financial Evidence', 'UK-Specific Documents', 'ukvi-financial-evidence'),
('UKVI Bank Statement', 'UK-Specific Documents', 'ukvi-bank-statement'),
('UKVI Sponsor Evidence', 'UK-Specific Documents', 'ukvi-sponsor-evidence'),
('UKVI Visa Application', 'UK-Specific Documents', 'ukvi-visa-application'),
('UKVI Decision Letter', 'UK-Specific Documents', 'ukvi-decision-letter'),
('UKVI Refusal Letter', 'UK-Specific Documents', 'ukvi-refusal-letter'),
('Biometric Appointment Letter', 'UK-Specific Documents', 'biometric-appointment-letter'),
('eVisa', 'UK-Specific Documents', 'evisa'),
('BRP Evidence', 'UK-Specific Documents', 'brp-evidence'),
('Academic Technology Approval Scheme Certificate', 'UK-Specific Documents', 'academic-technology-approval-scheme-certificate'),
('UK Accommodation Evidence', 'UK-Specific Documents', 'uk-accommodation-evidence'),
('UKVI Correspondence', 'UK-Specific Documents', 'ukvi-correspondence'),
('Previous UK Visa', 'UK-Specific Documents', 'previous-uk-visa'),
('Previous UK Visa Refusal', 'UK-Specific Documents', 'previous-uk-visa-refusal'),
('Medical Certificate', 'Medical Documents', 'medical-certificate'),
('Medical Examination Report', 'Medical Documents', 'medical-examination-report'),
('Medical Fitness Certificate', 'Medical Documents', 'medical-fitness-certificate'),
('Medical History', 'Medical Documents', 'medical-history'),
('Vaccination Record', 'Medical Documents', 'vaccination-record'),
('Immunization Record', 'Medical Documents', 'immunization-record'),
('Vaccination Certificate', 'Medical Documents', 'vaccination-certificate'),
('TB Test Certificate', 'Medical Documents', 'tb-test-certificate'),
('TB Screening Certificate', 'Medical Documents', 'tb-screening-certificate'),
('Medical Insurance Certificate', 'Medical Documents', 'medical-insurance-certificate'),
('Health Insurance', 'Medical Documents', 'health-insurance'),
('Medical Clearance', 'Medical Documents', 'medical-clearance'),
('Disability Documentation', 'Medical Documents', 'disability-documentation'),
('Medical Accommodation Letter', 'Medical Documents', 'medical-accommodation-letter'),
('Affidavit', 'Legal and Supporting Documents', 'affidavit'),
('Statutory Declaration', 'Legal and Supporting Documents', 'statutory-declaration'),
('Declaration Letter', 'Legal and Supporting Documents', 'declaration-letter'),
('Legal Declaration', 'Legal and Supporting Documents', 'legal-declaration'),
('Court Order', 'Legal and Supporting Documents', 'court-order'),
('Court Document', 'Legal and Supporting Documents', 'court-document'),
('Power of Attorney', 'Legal and Supporting Documents', 'power-of-attorney'),
('Guardianship Document', 'Legal and Supporting Documents', 'guardianship-document'),
('Custody Document', 'Legal and Supporting Documents', 'custody-document'),
('Adoption Certificate', 'Legal and Supporting Documents', 'adoption-certificate'),
('Legal Name Change Document', 'Legal and Supporting Documents', 'legal-name-change-document'),
('Police Clearance Certificate', 'Legal and Supporting Documents', 'police-clearance-certificate'),
('Criminal Record Certificate', 'Legal and Supporting Documents', 'criminal-record-certificate'),
('Character Certificate', 'Legal and Supporting Documents', 'character-certificate'),
('Good Conduct Certificate', 'Legal and Supporting Documents', 'good-conduct-certificate'),
('Certificate of Good Character', 'Legal and Supporting Documents', 'certificate-of-good-character'),
('Notarised Document', 'Legal and Supporting Documents', 'notarised-document'),
('Certified Copy', 'Legal and Supporting Documents', 'certified-copy'),
('Certified Translation', 'Legal and Supporting Documents', 'certified-translation'),
('Legal Translation', 'Legal and Supporting Documents', 'legal-translation'),
('Translation Certificate', 'Legal and Supporting Documents', 'translation-certificate'),
('Translator Declaration', 'Legal and Supporting Documents', 'translator-declaration'),
('Family Registration', 'Family and Relationship Documents', 'family-registration'),
('Family Tree Document', 'Family and Relationship Documents', 'family-tree-document'),
('Relationship Affidavit', 'Family and Relationship Documents', 'relationship-affidavit'),
('Proof of Relationship', 'Family and Relationship Documents', 'proof-of-relationship'),
('Spouse Evidence', 'Family and Relationship Documents', 'spouse-evidence'),
('Parent Evidence', 'Family and Relationship Documents', 'parent-evidence'),
('Child Birth Certificate', 'Family and Relationship Documents', 'child-birth-certificate'),
('Custody Order', 'Family and Relationship Documents', 'custody-order'),
('Accommodation Letter', 'Accommodation Documents', 'accommodation-letter'),
('Accommodation Booking', 'Accommodation Documents', 'accommodation-booking'),
('University Accommodation Confirmation', 'Accommodation Documents', 'university-accommodation-confirmation'),
('Tenancy Agreement', 'Accommodation Documents', 'tenancy-agreement'),
('Rental Agreement', 'Accommodation Documents', 'rental-agreement'),
('Lease Agreement', 'Accommodation Documents', 'lease-agreement'),
('Landlord Letter', 'Accommodation Documents', 'landlord-letter'),
('Landlord ID', 'Accommodation Documents', 'landlord-id'),
('Proof of Accommodation', 'Accommodation Documents', 'proof-of-accommodation'),
('Hotel Booking', 'Accommodation Documents', 'hotel-booking'),
('Temporary Accommodation Booking', 'Accommodation Documents', 'temporary-accommodation-booking'),
('Address Confirmation', 'Accommodation Documents', 'address-confirmation'),
('Council Tax Document', 'Accommodation Documents', 'council-tax-document'),
('Flight Reservation', 'Travel Documents', 'flight-reservation'),
('Flight Booking', 'Travel Documents', 'flight-booking'),
('Travel Itinerary', 'Travel Documents', 'travel-itinerary'),
('Previous Travel Visa', 'Travel Documents', 'previous-travel-visa'),
('Entry Stamp', 'Travel Documents', 'entry-stamp'),
('Exit Stamp', 'Travel Documents', 'exit-stamp'),
('Travel Insurance', 'Travel Documents', 'travel-insurance'),
('International Travel Insurance', 'Travel Documents', 'international-travel-insurance'),
('Certificate of Incorporation', 'Business Documents', 'certificate-of-incorporation'),
('Business Registration Certificate', 'Business Documents', 'business-registration-certificate'),
('CAC Certificate', 'Business Documents', 'cac-certificate'),
('CAC Form', 'Business Documents', 'cac-form'),
('Memorandum and Articles', 'Business Documents', 'memorandum-and-articles'),
('Company Profile', 'Business Documents', 'company-profile'),
('Business Licence', 'Business Documents', 'business-licence'),
('Business Permit', 'Business Documents', 'business-permit'),
('Tax Registration', 'Business Documents', 'tax-registration'),
('Tax Clearance', 'Business Documents', 'tax-clearance'),
('Company Tax Return', 'Business Documents', 'company-tax-return'),
('Business Bank Statement', 'Business Documents', 'business-bank-statement'),
('Audited Accounts', 'Business Documents', 'audited-accounts'),
('Director Information', 'Business Documents', 'director-information'),
('Shareholder Information', 'Business Documents', 'shareholder-information'),
('Business Ownership Evidence', 'Business Documents', 'business-ownership-evidence'),
('Business Contract', 'Business Documents', 'business-contract'),
('Invoice', 'Business Documents', 'invoice'),
('Business Agreement', 'Business Documents', 'business-agreement'),
('Professional Licence', 'Professional Qualification Documents', 'professional-licence'),
('Professional Registration', 'Professional Qualification Documents', 'professional-registration'),
('Professional Membership', 'Professional Qualification Documents', 'professional-membership'),
('Nursing Licence', 'Professional Qualification Documents', 'nursing-licence'),
('Medical Licence', 'Professional Qualification Documents', 'medical-licence'),
('Pharmacy Licence', 'Professional Qualification Documents', 'pharmacy-licence'),
('Engineering Licence', 'Professional Qualification Documents', 'engineering-licence'),
('Teaching Licence', 'Professional Qualification Documents', 'teaching-licence'),
('Accounting Qualification', 'Professional Qualification Documents', 'accounting-qualification'),
('ACCA Certificate', 'Professional Qualification Documents', 'acca-certificate'),
('ICAN Certificate', 'Professional Qualification Documents', 'ican-certificate'),
('CFA Certificate', 'Professional Qualification Documents', 'cfa-certificate'),
('PMP Certificate', 'Professional Qualification Documents', 'pmp-certificate'),
('Other Professional Qualification', 'Professional Qualification Documents', 'other-professional-qualification'),
('PhD Proposal', 'Research and PhD Documents', 'phd-proposal'),
('Research Plan', 'Research and PhD Documents', 'research-plan'),
('Published Research', 'Research and PhD Documents', 'published-research'),
('Conference Paper', 'Research and PhD Documents', 'conference-paper'),
('Conference Certificate', 'Research and PhD Documents', 'conference-certificate'),
('Supervisor Letter', 'Research and PhD Documents', 'supervisor-letter'),
('Supervisor Acceptance Letter', 'Research and PhD Documents', 'supervisor-acceptance-letter'),
('Research Supervisor Confirmation', 'Research and PhD Documents', 'research-supervisor-confirmation'),
('Funding Letter', 'Research and PhD Documents', 'funding-letter'),
('Research Funding Evidence', 'Research and PhD Documents', 'research-funding-evidence'),
('Publication List', 'Research and PhD Documents', 'publication-list'),
('Research Portfolio', 'Research and PhD Documents', 'research-portfolio'),
('Art Portfolio', 'Portfolio and Creative Documents', 'art-portfolio'),
('Design Portfolio', 'Portfolio and Creative Documents', 'design-portfolio'),
('Architecture Portfolio', 'Portfolio and Creative Documents', 'architecture-portfolio'),
('Photography Portfolio', 'Portfolio and Creative Documents', 'photography-portfolio'),
('Graphic Design Portfolio', 'Portfolio and Creative Documents', 'graphic-design-portfolio'),
('Fashion Portfolio', 'Portfolio and Creative Documents', 'fashion-portfolio'),
('Video Portfolio', 'Portfolio and Creative Documents', 'video-portfolio'),
('Creative Work Sample', 'Portfolio and Creative Documents', 'creative-work-sample'),
('Writing Portfolio', 'Portfolio and Creative Documents', 'writing-portfolio'),
('Project Portfolio', 'Portfolio and Creative Documents', 'project-portfolio'),
('GitHub Profile', 'Portfolio and Creative Documents', 'github-profile'),
('Coding Portfolio', 'Portfolio and Creative Documents', 'coding-portfolio'),
('Website Portfolio', 'Portfolio and Creative Documents', 'website-portfolio')
)
insert into public.document_types (owner_id, name, description, is_system, required_by_default, category, slug, display_order)
select null, c.name, 'System document type: ' || c.category, true, false, c.category, c.slug, row_number() over ()
from catalog c
where not exists (select 1 from public.document_types existing where lower(existing.name) = lower(c.name));
